# This is a basic workflow to help you get started with Actions

name: deploy bicep resources

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs the bicep CLI action - recursive + wildcard
      - name: Run Bicep build
        uses: aliencube/bicep-build-actions@v0.1
        with:
          files: '**/*.bicep'

      # Checks the result
      - name: Check the result
        shell: bash
        run: |
          shopt -s globstar
          ls -altR deploy/bicep/*.json

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy ARM template
        uses: Azure/arm-deploy@v1
        with:
          scope: 'resourcegroup'
          resourceGroupName: 'zapr-dev'
          template: deploy/bicep/aks.json
          deploymentMode: 'Complete'
      
      - uses: azure/setup-kubectl@v1
        with:
          version: 'latest'
        id: install

      uses: azure/aks-set-context@v1
        with:
            creds: '${{ secrets.AZURE_CREDENTIALS }}'
            resource-group: 'zapr-dev'
            cluster-name: 'zapraks01'
        id: login
      
      - name: Helm tool installer
        uses: Azure/setup-helm@v1.1

      - name: Run a multi-line script
        run: |
          helm repo add dapr https://daprio.azurecr.io/helm/v1/repo
          helm repo update
          kubectl create namespace dapr-system
          helm install dapr dapr/dapr --namespace dapr-system
          kubectl get pods -n dapr-system -w